spring:
  application:
    # Never use '_' in application name
    # Use '-' instead
    # Otherwise gateway may not work correctly
    name: notification

  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  # Message queue
  cloud:
    stream:
      kafka:
        binder:
          # 9092 is the default port of Kafka
          brokers: ${KAFKA_URL:localhost:9092}
      bindings:
        # https://docs.spring.io/spring-cloud-stream/reference/spring-cloud-stream/functional-binding-names.htm
        # Format: <method name>-<in or out>-<index>
        # receiveMessage: name of the method that receives the message
        # in: because is a consumer
        # 0: Index of the binding. This allows the same method to receive from multiple queues
        receiveNotification-in-0:
          destination: order-notification-queue
          group: order-notification-group
  mail:
    username: velasquitop204@gmail.com
    port: 587
    host: smtp.gmail.com
    password: jiqi uiuz ctja kwor
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        transport:
            protocol: smtp